### ISSUE TITLE
Start with a proper fork of the forgottenserver

### ISSUE THREAD

**Issue by Znote** [SaiyansKing/optimized_forgottenserver#1]
You can read about what a fork is and how to make it here:
https://help.github.com/en/articles/fork-a-repo

## Why work on a fork?
- Retain full revision history
- Git blame will actually work beside going back to "initial commit"
- Get included into the main repo's network
- Easier to do pull requests
- Easier to sync
- Easier to collaborate
- Merge pending pull requests from main repo (or any other repo in the network) without stealing their contribution credits
- Become a respectable bleeding edge repo of TFS, we appreciate more testers and developers in the scene. 
- Git gud

**Comment by SaiyansKing** [comment]
I'm sorry but I'll remain without fork, it is rather difficult to start with a roper fork now and since this repository going very different way than main repository it'll be hard to main sync with them.
