### ISSUE TITLE
Optimized new decay algorithm

### ISSUE THREAD

**Issue by Felipe6001** [SaiyansKing/optimized_forgottenserver#10]
@SaiyansKing
After I added this code to my source, I am unable to put together groupable items.
Example: https://imgur.com/JFlxzz9

**Comment by gerotib** [comment]
I can confirm it too, tested on unmodified code. That may be some attribute issue so they cant stack when it differ

**Comment by SaiyansKing** [comment]
Item stacking should work now after this commit:
https://github.com/SaiyansKing/optimized_forgottenserver/commit/0796e73ea97fda19068a16320f2089178958a0c2

**Comment by gerotib** [comment]
@SaiyansKing yah it seems fine now

**Comment by Felipe6001** [comment]
Well, it didn't work very well, it's still in trouble, another problem I found is when we create items. /i 9971.
Example: https://imgur.com/CwNRztg

**Comment by Felipe6001** [comment]
Now it is working correctly with the new commit.
[0ddab70](https://github.com/SaiyansKing/optimized_forgottenserver/commit/0ddab70333c2a2b78123b8b2af2e0616654f087b)

**Comment by Felipe6001** [comment]
@SaiyansKing 
One more problem when compiling on linux, on windows compiled normal.
https://imgur.com/wmqWIil
