### ISSUE TITLE
Memory skyrocket after player death after "Optimize Creature::conditions"

### ISSUE THREAD

**Issue by gerotib** [SaiyansKing/optimized_forgottenserver#11]
After this commit when player die, client freezes at "you are dead" window, and memory is ascending by couple gigabytes in cuple seconds. Something is clearly wrong ;)

**Comment by SaiyansKing** [comment]
My fault, I'm were not careful when erased this line "it = conditions.erase(it);" and it turned into infinite loop, thanks for your time in testing.
https://github.com/SaiyansKing/optimized_forgottenserver/commit/a8f509aedf6bdfcfd4274008c5aa24e11f5bd851

**Comment by gerotib** [comment]
Tested, fixed. Good job
