### ISSUE TITLE
Wrong paralyze calculation behaviour after Optimize Creature::conditions

### ISSUE THREAD

**Issue by gerotib** [SaiyansKing/optimized_forgottenserver#13]
It works fine when it calculate based of base speed, but it doesnt when player use some haste spell or wear speed equipment.

Vid from test (paralyze chance changed to 100%)
- [Being paralyzed and heal with base speed](https://gfycat.com/variablemedicalkingfisher)
- [Being paralyzed after haste spell](https://gfycat.com/granularmeatyamericanwarmblood) = speed changed to 7 and player "unable" to move

**Comment by SaiyansKing** [comment]
I'm sorry but I can't replicate it with spells that give me haste or items that give speed, also it doesn't have any sense because I didn't change any formula related to paralyze/haste so it still calculate how much speed it affects from base speed not total creature speed.

**Comment by gerotib** [comment]
@SaiyansKing hmm I actually didnt test that on most recent base I'll try to update and check again

**Comment by gerotib** [comment]
@SaiyansKing well this still happening, actually eq speed doesnt matter, but while healing paralyze with haste/strong haste its being messed up each time. With https://github.com/SaiyansKing/optimized_forgottenserver/commit/a8f509aedf6bdfcfd4274008c5aa24e11f5bd851 and https://github.com/SaiyansKing/optimized_forgottenserver/commit/14ed863a5a0cf33ae83e638de6b8400e2d4c4001 revert it works fine. I feel like it might changed some checks order so it doesn't work properly.

**Comment by gerotib** [comment]
Seems fine now :+1:
