### ISSUE TITLE
Character saving fix breaks battle window

### ISSUE THREAD

**Issue by gerotib** [SaiyansKing/optimized_forgottenserver#2]
I realised that I am unable to select monster directly from battle window, and after reverting these commits it works fine. Thats probably because of these AutoID ranges being changed.

**Comment by SaiyansKing** [comment]
Thanks for mentioning this, I'm make this bug by mistake was just checking something and forget to swap back to real MonsterID and NPCID(I'm surprised they still checking for these id's because creatures have "type" which indicate if they are monster, npc etc sended by server).
