### ISSUE TITLE
Bug in linux make (compilation zlib)

### ISSUE THREAD

**Issue by luisbill1** [SaiyansKing/optimized_forgottenserver#20]
After i added the "compress packet commit" i have this error when i try to compile my tfs: (ubuntu 18.04)

/usr/bin/ld: /tmp/ccg9lNwv.ltrans7.ltrans.o: undefined reference to symbol 'deflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/tfs.dir/build.make:2526: recipe for target 'tfs' failed
make[2]: *** [tfs] Error 1
CMakeFiles/Makefile2:163: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SaiyansKing** [comment]
It was fixed in later commit(I suggest that you avoid cherry picking from this repository):
https://github.com/SaiyansKing/optimized_forgottenserver/commit/e9c194264a9e8c0ae2d3e9e9aa348904605c172b
