### ISSUE TITLE
Talkactions & spells optimizations errors

### ISSUE THREAD

**Issue by strndi** [SaiyansKing/optimized_forgottenserver#21]
I have tried your talkactions & spell optimizations, they work good, but the behaviour of these systems is not exactly as they should be. 

1.  The param from a talkaction message is now always lowercase, this affects broadcast command, but can also affect other things.  "/B This Is a Message With Capital letters."  becomes: 01:11 Merkels: this is a message with capital letters.

2. You can no longer use spells that contains params without including " in the spell. On normal TFS, you can cast exura sio by typing: exura sio Merkels.
This is what happens with changes from this distro: 01:14 Merkels [4160]: exura sio Merkels
The spell is not cast at all, when infact it should be cast on the player, even if you didn't include " inside your spell message.

3. If you cast a spell with a completely empty param, like for example typing: 'exiva "' then it will just send 'exiva "' as a message in the game, but the old behaviour is that it should try to cast exiva. 

4. You have to register spells and talkactions with lowercases in XML files, while previously you could have spells starting with uppercase in XML Files. (this issue probably be ignored as it's not that important)

I believe 2 and 1 are quite important fixes, as I have seen plenty of players failing to cast spells because of those changes, and talkactions not recognizing upper case letters ruins things like broadcasts, and guild broadcasts.

**Comment by SaiyansKing** [comment]
1. Talkactions were fixed in later commit(I suggest that you avoid cherry picking from this repository as it is not necessary compatible and might result in crash bugs on other engines).

2. Who decided that this is bug? Just because it works incorrectly somewhere doesn't mean I need to maintain the same behavior, this repository is meant to be optimal and be true to the real Tibia. You can't cast spell in that way on real Tibia.

3. So what? It works like that on real Tibia.

4. As I wrote in 1 the talkactions were fixed and as for spells I never seen someone write words to cast in uppercase.

**Comment by strndi** [comment]
> 1. Talkactions were fixed in later commit(I suggest that you avoid cherry picking from this repository as it is not necessary compatible and might result in crash bugs on other engines).
> 2. Who decided that this is bug? Just because it works incorrectly somewhere doesn't mean I need to maintain the same behavior, this repository is meant to be optimal and be true to the real Tibia. You can't cast spell in that way on real Tibia.
> 3. So what? It works like that on real Tibia.
> 4. As I wrote in 1 the talkactions were fixed and as for spells I never seen someone write words to cast in uppercase.

Thanks for your reply, and your changes are really great. 
I tested 2 and 3 in real tibia, you are correct about 3. But you can clearly cast param spells in real tibia, without including ". I just downloaded real tibia, and typing "exani hur up" works for that spell, same with exura - so that is infact a bug if you want to match real tibia.

**Comment by Czopeq** [comment]
https://tibia.fandom.com/wiki/Spells

Check how to cast: Levitate
"same with exiva" - nope.

**Comment by strndi** [comment]
> https://tibia.fandom.com/wiki/Spells
> 
> Check how to cast: Levitate
> "same with exiva" - nope.

I literally just tested it on real tibia, rofl
