### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by EPuncker** [SaiyansKing/optimized_forgottenserver#26]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. I changed definitions.h to 860 (right, right?)
2. opened theforgottenserver.sln (it told me to update to latest version tho)
3. I changed to release and x64
4. boom

### Expected behaviour
successful compilation (?)

### Actual behaviour
https://pastebin.com/raw/6YfjfCyb

### Environment
Windows 10
MSVC 2019 (installed gmp thru (vcpckg install gmp))

### Disclaimer
I don't know if it is an actual issue, or just a mistake from my part, but wanted to report it anyway

**Comment by SaiyansKing** [comment]
I've just removed experimental filesystem and as for gmp if it is problematic you can try using mpir (vcpckg install mpir:x86-windows mpir:x64-windows)

**Comment by EPuncker** [comment]
> 1>------ Build started: Project: theforgottenserver, Configuration: Release x64 ------
> 1>LINK : fatal error LNK1181: cannot open input file 'libmysql.lib'
> 1>Done building project "theforgottenserver.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I think I'm almost there, what is missing now? (I can compile any other distro fine so I have no idea what might be wrong)

**Comment by HeberPcL** [comment]
same problem for me

![image](https://user-images.githubusercontent.com/715547/95802847-f0f32a00-0cd4-11eb-8c6b-4ac24d5a969d.png)

**Comment by SaiyansKing** [comment]
It just that the base for this repository is the old version that was made for 2017 with downloadable tfs sdk not for vcpkg so it needs standard mysql lib but you probably have mariadb installed, I think changing libmysql.lib to libmariadb.lib in settings.props should do the work. Since it works for me I didn't change.

**Comment by HeberPcL** [comment]
I did it, configured the SDK, added the zlib library to SDK 3.2. I now have other errors.

`1>C:\local\boost_1_40_0\boost\iostreams\positioning.hpp(96,1): warning C4996: 'std::fpos<_Mbstatet>::seekpos': warning STL4019: The member std::fpos::seekpos() is non-Standard, and is preserved only for compatibility with workarounds for old versions of Visual C++. It will be removed in a future release, and in this release always returns 0. Please use standards-conforming mechanisms to manipulate fpos, such as conversions to and from streamoff, or an integral type, instead. If you are receiving this message while compiling Boost.IOStreams, a fix has been submitted upstream to make Boost use standards-conforming mechanisms, as it does for other compilers. You can define _SILENCE_FPOS_SEEKPOS_DEPRECATION_WARNING to acknowledge that you have received this warning, or define _REMOVE_FPOS_SEEKPOS to remove std::fpos::seekpos entirely. (compiling source file ..\src\chat.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\iosfwd(74): message : see declaration of 'std::fpos<_Mbstatet>::seekpos' (compiling source file ..\src\chat.cpp)`

**Comment by EPuncker** [comment]
that is not an error just a warning, you can ignore it ^^
btw after fixing the libmysql.lib issue it asked for zlib1, then I installed zlib, changed zlib**1** to zlib in the settings.props file and everything compiled smoothly, thanks for the help!
