### ISSUE TITLE
Server crash after decay optimizations

### ISSUE THREAD

**Issue by gerotib** [SaiyansKing/optimized_forgottenserver#29]
First of all I am not completely sure if thats pure optimized tfs issue, because I am using otservbr as a base, but crashlog show `Container::stopDecaying()` which was [added along](https://github.com/SaiyansKing/optimized_forgottenserver/commit/16a43ffc039f20e26acaad726ebc5f44c75ebe9b#diff-f1a2300b7a53a23b80600cead0ff2900839a41ceb0e22633bd1db9cfdd08e2ac) with decay optimizations in this project (thats not a part of base otbr, I added that myself). For couple days I am running test server with average of 10-20 players, and crash only happens 1-2x per day, while some player logs off. Heres [crashlog](https://pastebin.com/vfZPm8vS). It seems pretty random, and I am unable to reproduce this crash. Players which logout is causing crash seems to have only basic items and mostly none of decaying ones. I dont know if you will be able to fix that from crashlog only (well if thats actual issue here), or I could add some prints that could help. As for now I would probably revert these changes from my server, but I wanted to inform about it anyway.

**Comment by joseluis2g** [comment]
so you added code from this repo to your otbr project and because of that some strange bug appears? any script related to it?

**Comment by SaiyansKing** [comment]
It is problem with their global depot system that result in dangling pointers because it is coded in unsafe manner. Already discussed about this on their project page when they wanted to cherry pick depot memory free fix.
Not my fault that they didn't fixed it.

**Comment by gerotib** [comment]
@SaiyansKing Yeah I already found out thats depot memory leak fix fault, not decay itself. Thanks for reply, I'll close as it's not this project fault.
