### ISSUE TITLE
Monster Walk Back to Spawn [feature suggestion]

### ISSUE THREAD

**Issue by Diego-OT** [SaiyansKing/optimized_forgottenserver#30]
As in the global, monsters must return to their spawn _walking_ when they lose the target.
So avoiding the monsters being lured in the map.
Suggestion that as soon as the monster reaches its destination, enter Idle mode.

**Comment by SaiyansKing** [comment]
I'll make this feature but first I need to implement different jps pathfinding method that are optimized for long distances(current A* algorithm will perform terribly and in most cases might not even find path to spawn since it has that much limited node count).
