### ISSUE TITLE
STORE bugs

### ISSUE THREAD

**Issue by Skazzzi** [SaiyansKing/optimized_forgottenserver#33]
after open store i get that error
`Lua Script Error: [Main Interface]
(Unknown scriptfile)
attempt to call a nil value
stack traceback:
        [C]: at 0x557d01aef234
`
[https://i.imgur.com/3sfNrqS.png](url)

**Comment by SaiyansKing** [comment]
Not enough information about issue.
Use bug report template for future or it'll be instant close.
