### ISSUE TITLE
Closed.

### ISSUE THREAD

**Issue by Ezipsoft** [SaiyansKing/optimized_forgottenserver#39]
My bad, sorry.

**Comment by SaiyansKing** [comment]
> now it was possible to use stairs while away, also affected the creatures walk and area spells,

So it was possible or it is now possible? I can't use stairs while being away from them.
About creatures and spells for me they work correctly so you must have do something wrong.

![Img1](https://i.ibb.co/rf7rgK9/1.png)
![Img2](https://i.ibb.co/Xysmtr2/2.jpg)

**Comment by Ezipsoft** [comment]
> > now it was possible to use stairs while away, also affected the creatures walk and area spells,
> 
> So it was possible or it is now possible? I can't use stairs while being away from them.
> About creatures and spells for me they work correctly so you must have do something wrong.
> 
> ![Img1](https://camo.githubusercontent.com/75f9ab50bc966d2df9897eca232916ee13152eaa097798c78e3f96abde896851/68747470733a2f2f692e6962622e636f2f72663772674b392f312e706e67)
> ![Img2](https://camo.githubusercontent.com/67f56162e8cf031428898bbb559eb1b38b4cec564a0c0f3810ead11f6de19c22/68747470733a2f2f692e6962622e636f2f5879736d7472322f322e6a7067)

Really sorry, made some mistake on position.h
