### ISSUE TITLE
 possible problem spawn size

### ISSUE THREAD

**Issue by Chapeleiiro** [SaiyansKing/optimized_forgottenserver#46]
when the creature leaves the spawn size it doesn’t need to die to be born again

![image](https://user-images.githubusercontent.com/21350343/106847676-21990e00-668e-11eb-84f4-c1eddd5a8032.png)

**Comment by SaiyansKing** [comment]
I'm sorry, but I don't understand what you mean.
It doesn't make any sense for monsters to respawn when they leave their spawn and in my opinion behavior like this is simply a bug. I'll stick with behavior that they'll not respawn, however they go back to their respawn when they go into idle but lately I hardly have time to do anything for this project so it'll not be coded soon.

ps. why is it so hard to use issue template and write properly what is the problem?

**Comment by Chapeleiiro** [comment]
ok
