### ISSUE TITLE
Party List Behaviour 12.30+

### ISSUE THREAD

**Issue by FakeShinoda** [SaiyansKing/optimized_forgottenserver#47]
Hi master.

Looks like cip client has the party list management since version 12.30, im actually not using any party list functions and all seems work perfect unless the mana bar.. that still need to be sended server side.
On 12.30 client in some rare cases when you are in party and get teleported you game window (only you field of view) gets black. (with you party list)

![party](https://user-images.githubusercontent.com/23365432/108724909-9b415080-7504-11eb-971a-162a79e9ca22.png)

**Comment by SaiyansKing** [comment]
> Hi master.
> 
> Looks like cip client has the party list management since version 12.30, im actually not using any party list functions and all seems work perfect unless the mana bar.. that still need to be sended server side.

So you mean that you don't use this repository or that you use it without the party list support commit?

> On 12.30 client in some rare cases when you are in party and get teleported you game window (only you field of view) gets black. (with you party list)
> 
> ![party](https://user-images.githubusercontent.com/23365432/108724909-9b415080-7504-11eb-971a-162a79e9ca22.png)

Does it happen completely randomly or it happens in specific places? Because after testing it for some time I can't replicate the black screen bug.

**Comment by FakeShinoda** [comment]
Im using this repo but im removed the party list commit because in some very rare cases (like getting teleport to very far regions) some players get thier screen black. When i removed the commit this behaviour disapear, and the party list feature still working (unless the mana bar).

**Comment by FakeShinoda** [comment]
I was never able to reproduce this, only a few players experienced this behavior.

But the conclusion I drew is that there was some conflict between the packages sent and the client dealing with the feature automatically.

**Comment by SaiyansKing** [comment]
> Im using this repo but im removed the party list commit because in some very rare cases (like getting teleport to very far regions) some players get thier screen black. When i removed the commit this behaviour disapear, and the party list feature still working (unless the mana bar).

> I was never able to reproduce this, only a few players experienced this behavior.
> 
> But the conclusion I drew is that there was some conflict between the packages sent and the client dealing with the feature automatically.

Packets conflict should result in client crash rather than black screen and the packets are correct. It only theoretically work without the party list commit(it doesn't update character display state too not only mana bar) also I've remembered now that in some commit later I fixed wrong creature pointer that could result in wrong character state(it is possible that it was the problem with black screen).

**Comment by FakeShinoda** [comment]
Right, i'll check the commits later related to that. Thanks for the attention.
