### ISSUE TITLE
ZLIB_INCLUDE_DIR

### ISSUE THREAD

**Issue by Chapeleiiro** [SaiyansKing/optimized_forgottenserver#8]
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro	LNK1104	não é possível abrir o arquivo 'zlib1.lib'	theforgottenserver	C:\Users\...\Downloads\optimized_forgottenserver-master\vc14\LINK	1

**Comment by SaiyansKing** [comment]
Use english here, if you have zlib dependency problem then everything you need to do is download precompiled libraries or compile one yourself.
