### ISSUE TITLE
Items stop decay after being moved

### ISSUE THREAD

**Issue by gerotib** [SaiyansKing/optimized_forgottenserver#9]
I tested that on 10.98 protocol, but I believe it doesn't matter.

To reproduce:
1. /i 2163 (or any other item that decays)
2. move it to the ground/ another container etc.
3. item does not decay anymore

It was partially fixed with https://github.com/otland/forgottenserver/commit/d1e3e6d328d070b8f49e1c5de01c70b02fd5ae7d on main tfs repo.

**Comment by SaiyansKing** [comment]
Thanks for reporting this issue, I'll debug it to detect all cases where it stops decaying/don't start decaying when it should/shouldn't and try to fix it today.

The problem with tfs is that the more you review code the more you see how broken it is and fixing everything is masochism but I'll try my best.

**Comment by gerotib** [comment]
Yeah these issues like decay or condition ones resides in tfs from like forever, and whole code is so chaotic that noone is willing to adress and fix them, cause it's pretty masochistic work as you said.

**Comment by gerotib** [comment]
@SaiyansKing Only decay issue I found now, is that monsters does not start to decay after death. I found that it broke after this change https://github.com/SaiyansKing/optimized_forgottenserver/commit/f7429eaf4d75a0740325f5c3ed708e91348bdd99#diff-d692aa92dfdf2ae98d790503b68ad865 (with `g_game.startDecay(corpse);` after first corpse check it seems to work fine)

**Comment by SaiyansKing** [comment]
Should be fixed now, for some reason I thought that iterating through container should put that container itself to decaying state xD
